version: 2

project_name: s3-browser

builds:
  - id: s3-browser-linux-amd64
    main: .
    binary: s3-browser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

archives:
  - id: s3-browser-linux-amd64
    ids:
      - s3-browser-linux-amd64
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: SCcagg5
    name: S3-Browser
